ContratoQR.WEB/Models/MensajeriaViewModel.cs
namespace ContratoQR.WEB.Models
{
    public class MensajeriaViewModel
    {
        public string? Url { get; set; }
        public string? Mensaje { get; set; }
        public bool IsError { get; set; }
    }
}

ContratoQR.WEB/Controllers/CodigoQRController.cs
using ContratoQR.Entity;
using ContratoQR.WEB.Models;
using ExcelDataReader;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Diagnostics;

namespace ContratoQR.WEB.Controllers
{
    public class CodigoQRController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public CodigoQRController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public ActionResult Index()
        {
            FileExcelViewModel fileExcelModel = new FileExcelViewModel();
            ViewData["qr"] = "";
            ViewBag.QR = "";
            fileExcelModel.CodigoQR = "";
            fileExcelModel.NombreFuncionario = "";
            fileExcelModel.UrlContrato = "";

            return View(fileExcelModel);
        }

        [HttpPost]
        public Task<IActionResult> Index(string texto)
        {
            List<FileExcelEntity> funcionarios = new List<FileExcelEntity>();
            string? filePath = ""; // _configuration.GetValue<string>("NombreExcel").ToString();
            FileExcelViewModel fileExcelModel = new FileExcelViewModel();

            if (Directory.Exists(Path.Combine("wwwroot", "Uploads")) && Directory.GetFiles(Path.Combine("wwwroot", "Uploads")).Length > 0)
            {
                filePath = Directory.GetFiles(Path.Combine("wwwroot", "Uploads"))[0];
            }
            else
            {
                fileExcelModel.Mensaje = "No se ha subido el archivo Excel.";
                fileExcelModel.IsError = "SI";
                return Task.FromResult<IActionResult>(View(fileExcelModel));
            }

            if (texto == null)
            {
                ViewData["mensaje"] = "Introduzca Rut del Funcionario";
                return Task.FromResult<IActionResult>(View());
            }

            using (var stream = new FileStream(filePath, FileMode.Open, FileAccess.Read))
            {
                using (var reader = ExcelReaderFactory.CreateReader(stream))
                {
                    var result = reader.AsDataSet();

                    foreach (DataRow fila in result.Tables[0].Rows)
                    {

                        funcionarios.Add(
                            new FileExcelEntity
                            {
                                RutFuncionario = fila[0].ToString()!.Replace("-", "").Replace(".", ""),
                                NombreFuncionario = fila[1].ToString(),
                                UrlContrato = fila[2].ToString()
                            });
                    }
                }
            }

            fileExcelModel.Funcionarios = funcionarios;
            fileExcelModel.Funcionario = fileExcelModel.Funcionarios.Where(f => f.RutFuncionario == texto.Replace("-", "").Replace(".", "")).FirstOrDefault();

            Helpers.HelperQR helperQR = new Helpers.HelperQR();
            fileExcelModel.CodigoQR = helperQR.GenerateQRCode(fileExcelModel.Funcionario != null ? fileExcelModel.Funcionario.UrlContrato : "No encontrado");
            fileExcelModel.NombreFuncionario = fileExcelModel.Funcionario == null ? "No encontrado" : fileExcelModel.Funcionario.NombreFuncionario;
            fileExcelModel.UrlContrato = fileExcelModel.Funcionario == null ? "No encontrado" : fileExcelModel.Funcionario.UrlContrato;

            return Task.FromResult<IActionResult>(View(fileExcelModel));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ContratoQR.WEB/Controllers/EncuestaController.cs
using ClosedXML.Excel;
using ContratoQR.Entity;
using ContratoQR.WEB.Models;
using DocumentFormat.OpenXml.InkML;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Data;

namespace ContratoQR.WEB.Controllers
{
    public class EncuestaController : Controller
    {

        private readonly IConfiguration _configuration;

        public EncuestaController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            EncuestaViewModel encuestaViewModel = new();
            BLL.Encuesta encuesta = new();

            try
            {
                encuestaViewModel.ListaCantidad = encuesta.ListarCantidad(_configuration);
                encuestaViewModel.resultadoEncuestas = encuesta.ListarResultadoEncuesta(_configuration);
                encuestaViewModel.CantidadTotalRespuestas = encuestaViewModel.resultadoEncuestas.Count();
                encuestaViewModel.CantidadEncuestasCompletadas = encuestaViewModel.resultadoEncuestas.Count() / 3;
            }
            catch (Exception ex)
            {
                return PartialView("Mensajeria", new MensajeriaViewModel { IsError = true, Mensaje = ex.Message, Url = "/Encuesta" });
            }

            return View(encuestaViewModel);
        }

        [HttpGet]
        public FileResult ExportarExcel()
        {
            var nombreArchivo = $"ResultadoEncuesta.xlsx";

            EncuestaViewModel encuestaViewModel = new();
            BLL.Encuesta encuesta = new();

            encuestaViewModel.resultadoEncuestas = encuesta.ListarResultadoEncuesta(_configuration);

            return GenerarExcel(nombreArchivo, encuestaViewModel.resultadoEncuestas);
        }

        private FileResult GenerarExcel(string nombreArchivo, IEnumerable<ResultadoEncuestaEntity> resultadoEncuestas)
        {
            DataTable dataTable = new DataTable("Personas");
            dataTable.Columns.AddRange(new DataColumn[]
            {
                new DataColumn("DescripcionPregunta"),
                new DataColumn("DescripcionValorRespuesta")
            });

            foreach (var resultado in resultadoEncuestas)
            {
                dataTable.Rows.Add(resultado.DescripcionPregunta, resultado.DescripcionValorRespuesta);
            }

            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dataTable);

                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(),
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        nombreArchivo);
                }
            }

        }

    }
}

ContratoQR.WEB/Controllers/FuncionarioController.cs
using ContratoQR.Entity;
using ContratoQR.WEB.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Drawing;

namespace ContratoQR.WEB.Controllers
{
    public class FuncionarioController : Controller
    {
        private readonly IConfiguration _configuration;

        public FuncionarioController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            PersonalViewModel personalViewModel = new();
            BLL.Personal personal = new();

            try
            {
                personalViewModel.ListaPersonal = personal.Listar(string.Empty, string.Empty, _configuration);
            }
            catch (Exception ex)
            {
                return PartialView("Mensajeria", new MensajeriaViewModel { IsError = true, Mensaje = ex.Message, Url = "/Funcionario" });
            }

            return View(personalViewModel);
        }

        [HttpPost]
        public IActionResult GetFuncionario(string rutFuncionario, string nombreFuncionario)
        {
            PersonalViewModel personalViewModel = new();
            BLL.Personal personal = new();

            try
            {
                rutFuncionario = rutFuncionario ?? string.Empty;
                nombreFuncionario = nombreFuncionario ?? string.Empty;

                personalViewModel.ListaPersonal = personal.Listar(rutFuncionario, nombreFuncionario, _configuration);
            }
            catch (Exception ex)
            {
                return PartialView("Mensajeria", new MensajeriaViewModel { IsError = true, Mensaje = ex.Message, Url = "/Funcionario" });
            }

            return View("Index", personalViewModel);
        }

        public IActionResult Create()
        {
            PersonalViewModel personalViewModel = new();
            BLL.Personal personal = new();

            return View(personalViewModel);
        }

        [HttpPost]
        public IActionResult Create(IFormCollection formulario)
        {
            BLL.Personal personal = new();
            PersonalViewModel personalViewModel = new();
            PersonalEntity personalQREntity = new();

            try
            {
                //personalQREntity.RutFuncionario = formulario["RutFuncionario"].ToString().ToUpper();
                //personalQREntity.NombreFuncionario = formulario["NombreFuncionario"].ToString().ToUpper();
                //personalQREntity.UrlContrato = formulario["UrlContrato"];
                //personalQREntity.IndEstado = 1;

                //personal.Insertar(personalQREntity, _configuration);

                personalViewModel.ListaPersonal = personal.Listar(string.Empty, string.Empty, _configuration);
            }
            catch (Exception ex)
            {
                return PartialView("Mensajeria", new MensajeriaViewModel { IsError = true, Mensaje = ex.Message, Url = "/Funcionario" });
            }

            return PartialView("Mensajeria", new MensajeriaViewModel { IsError = false, Mensaje = "Registro creado!!!", Url = "/Funcionario" });
        }

        public IActionResult Edit(string rutPersonal)
        {
            PersonalViewModel personalViewModel = new();
            BLL.Personal personal = new();

            try
            {
                personalViewModel.ListaPersonal = personal.Listar(rutPersonal, string.Empty, _configuration);

                if (personalViewModel.ListaPersonal.Count == 0)
                {
                    return RedirectToAction("Index");
                }

                //personalViewModel.RutFuncionario = personalViewModel.ListaPersonal[0].RutFuncionario;
                //personalViewModel.NombreFuncionario = personalViewModel.ListaPersonal[0].NombreFuncionario;
                //personalViewModel.UrlContrato = personalViewModel.ListaPersonal[0].UrlContrato;
                //personalViewModel.IdPersonalQR = personalViewModel.ListaPersonal[0].IdPersonalQR;
            }
            catch (Exception ex)
            {
                return PartialView("Mensajeria", new MensajeriaViewModel { IsError = true, Mensaje = ex.Message, Url = "/Funcionario" });
            }

            return View(personalViewModel);

        }

        [HttpPost]
        public IActionResult Edit(IFormCollection formulario)
        {
            BLL.Personal personal = new();
            PersonalEntity personalQREntity = new();
            PersonalViewModel personalViewModel = new();

            try
            {
                //personalQREntity.IdPersonalQR = Convert.ToInt32(formulario["IdPersonalQR"]);
                //personalQREntity.RutFuncionario = formulario["RutFuncionario"].ToString().ToUpper();
                //personalQREntity.NombreFuncionario = formulario["NombreFuncionario"].ToString().ToUpper();
                //personalQREntity.UrlContrato = formulario["UrlContrato"];
                //personalQREntity.IndEstado = 1;

                personalViewModel.ListaPersonal = personal.Listar(string.Empty, string.Empty, _configuration);

                //personal.Actualizar(personalQREntity, _configuration);
            }
            catch (Exception ex)
            {
                return PartialView("Mensajeria", new MensajeriaViewModel { IsError = true, Mensaje = ex.Message, Url = "/Funcionario" });
            }

            return PartialView("Mensajeria", new MensajeriaViewModel { IsError = false, Mensaje = "Funcionario actualizado!!!", Url = "/Funcionario" });

        }
    }
}

ContratoQR.WEB/Controllers/UploadFileController.cs
using ContratoQR.WEB.Models;
using Microsoft.AspNetCore.Mvc;

namespace ContratoQR.WEB.Controllers
{
    public class UploadFileController : Controller
    {
        public IActionResult Index()
        {
            FileExcelViewModel fileExcelModel = new FileExcelViewModel();

            fileExcelModel.IsError = "";

            return View(fileExcelModel);
        }

        [HttpPost]
        public async Task<IActionResult> FileUpload(IFormFile file)
        {

            FileExcelViewModel fileExcelModel = new FileExcelViewModel();
            ViewBag.Inicio = "NO";

            try
            {
                if (file != null && file.Length > 0)
                {
                    var uploadsPath = Path.Combine("wwwroot", "Uploads"); // Asegúrate que esta carpeta existe
                    if (Directory.Exists(uploadsPath))
                    {
                        Directory.Delete(uploadsPath, true);
                        Directory.CreateDirectory(uploadsPath);
                    }
                    else
                    {
                        Directory.CreateDirectory(uploadsPath);
                    }

                    var filePath = Path.Combine(uploadsPath, file.FileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                }
            }
            catch (Exception ex)
            {
                return PartialView("Mensajeria", new MensajeriaViewModel { IsError = true, Mensaje = ex.Message, Url = "/Home" });
            }

            return PartialView("Mensajeria", new MensajeriaViewModel { IsError = false, Mensaje = "Archivo subido exitosamente", Url = "/Home" });
        }
    }
}

ContratoQR.WEB/Views/Shared/Mensajeria.cshtml
@model MensajeriaViewModel

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Mensaje - ContratoQR - Prestadores de Servicios Depto. Salud - Quilicura</title>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    @{
        if (Model.Url!.StartsWith("/"))
        {
            Model.Url = Url.Content("~" + Model.Url);
        }
    }

    @if (!Model.IsError)
    {
        <script>
            Swal.fire({
                icon: 'success',
                title: '@Html.Raw(Model.Mensaje)',
                confirmButtonText: "OK",
                text: ''
            }).then((result) =>
            {
                if (result.isConfirmed)
                {
                    window.location.href = '@Model.Url';
                }
            }
            );
        </script>
    }
    else if (Model.IsError)
    {
        <script>
            Swal.fire({
                icon: 'error',
                title: '@Html.Raw(Model.Mensaje)',
                confirmButtonText: "OK",
                text: ''
            }).then((result) =>
            {
                if (result.isConfirmed)
                {
                    window.location.href = '@Model.Url';
                }
            }
            );
        </script>
    }
</body>

</html>

ContratoQR.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ContratoQR - Prestadores de Servicios Depto. Salud - Quilicura</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet " href="~/css/gridmvc.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.10.0/css/bootstrap-datepicker.min.css" integrity="sha512-34s5cpvaNG3BknEWSuOncX28vz97bRI59UnVtEEpFX536A7BtZSJHsDyFoCl8S7Dt2TPzcrCEoHBGeM4SUBDBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/webContratoQR.styles.css" asp-append-version="true" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
   @*  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.5.0/chart.min.js" type="text/javascript"></script> *@

</head>
<body>

    <!-- Inicio del menu -->
    <header>
        <div class="left">
            <div class="menu-container">
                <div class="menu" id="menu">
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>
            <div class="brand">
                <span class="name">Prestadores de Servicios Depto. Salud - Quilicura</span>
            </div>
        </div>
        <div class="brand">
            <a asp-controller="Home" asp-action="Index"><img src="img/QuilicuraSalud.png" alt="" style="height: 8%; width: 8%; float: right;" /></a>
        </div>
    </header>

    @* Menú *@
    <div class="sidebar" id="sidebar">
        <nav>
            <ul>
                <li>
                    <a asp-controller="Home" asp-action="Index" class="selected">
                        <img src="~/icons/home-menu.svg" alt="" />
                        <span>Inicio</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="CodigoQR" asp-action="Index">
                        <img src="~/icons/CodigoQR.svg" alt="" />
                        <span>Generar QR</span>
                    </a>
                </li>
                <li>
                    <a asp-controller="UploadFile" asp-action="Index">
                        <img src="~/icons/UploadFile.svg" alt="" />
                        <span>Subir Archivo</span>
                    </a>
                </li>
@*                 <li>
                    <a asp-controller="Funcionario" asp-action="Index">
                        <img src="~/icons/user-menu.svg" alt="" />
                        <span>Funcionario</span>
                    </a>
                </li> *@
                <li>
                    <a asp-controller="Encuesta" asp-action="Index">
                        <img src="~/icons/Encuesta.svg" alt="" />
                        <span>Encuesta</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>

    <div class="container">
        <main role="main" class="pb-3" id="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Contrato QR - Prestadores de Servicios Depto. Salud - Quilicura
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/js/gridmvc.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.10.0/js/bootstrap-datepicker.min.js" integrity="sha512-LsnSViqQyaXpD4mBBdRYeP6sRwJiJveh2ZIbW41EBrNmKxgr/LFZIiWT6yr+nycvhvauz8c2nYMhrP80YhG7Cw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>